package ca.bc.gov.educ.api.graduation.util;

public interface PermissionsContants {
	String _PREFIX = "hasAuthority('";
	String _SUFFIX = "')";

	String GRADUATE_STUDENT = _PREFIX + "SCOPE_UPDATE_GRAD_GRADUATION_STATUS" + _SUFFIX + " and " + _PREFIX + "SCOPE_RUN_GRAD_ALGORITHM" + _SUFFIX;
	String GRADUATE_DATA = _PREFIX + "SCOPE_GET_GRADUATION_DATA" + _SUFFIX;
	String GRADUATE_TRANSCRIPT = _PREFIX + "SCOPE_GET_GRADUATION_TRANSCRIPT" + _SUFFIX;
	String GRADUATE_CERTIFICATE = _PREFIX + "SCOPE_GET_GRADUATION_CERTIFICATE" + _SUFFIX;
	String GRADUATE_ACHIEVEMENT = _PREFIX + "SCOPE_GET_GRADUATION_ACHIEVEMENT" + _SUFFIX;
}
