#DB Properties
spring:
  jmx:
    enabled: false
  mvc:
    log-request-details: ${SPRING_SHOW_REQUEST_DETAILS}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  #Keycloak/OAuth properties
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TOKEN_ISSUER_URL}
          jwk-set-uri: ${TOKEN_ISSUER_URL}/protocol/openid-connect/certs

#Logging properties
logging:
  file:
    name: /logs/app.log
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 20MB
      clean-history-on-start: true
  pattern:
    #  file: "%d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n"
    #  console: "%d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n"
    file: '{"time_stamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%3p" ,"thread":"%t" ,"class":"%logger{36}","msg":"%replace(%msg){"[\n\r\"]",""}", "exception":"%replace(%rEx{10}){"[\n\r\"]",""}","http_event":%X{httpEvent:-""},"message_event":%X{messageEvent:-""}}%nopex%n'
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%5p] [%t] [%logger{36}] [%replace(%msg){'[\n\r]',''} %X{httpEvent} %X{messageEvent}] %replace(%rEx{10}){'[\n\r]',''}%nopex%n"
  level:
    ca:
      bc:
        gov:
          educ:
            api:
              graduation: ${APP_LOG_LEVEL}
    org:
      springframework:
        web: ${SPRING_WEB_LOG_LEVEL}
        security: ${SPRING_SECURITY_LOG_LEVEL}
        boot:
          autoconfigure:
            logging: ${SPRING_BOOT_AUTOCONFIG_LOG_LEVEL}

#Local properties
server:
  undertow:
    threads:
      worker: 128
      io: 16
  #port: ${HTTP_PORT}

authorization:
  user: ${GRAD_CLIENT_NAME}
  password: ${GRAD_CLIENT_SECRET}

#API Documentation
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/api-docs-ui.html
    operationsSorter: alpha

#Endpoints
endpoint:
 keycloak:
  getToken: ${KEYCLOAK_TOKEN_URL}auth/realms/master/protocol/openid-connect/token
 grad-student-api: 
  update-grad-status: ${GRAD_STUDENT_API}api/v1/student/studentid/%s
  read-grad-student-record: ${GRAD_STUDENT_API}api/v1/student/studentid/%s/algorithm
  save-optional-program-grad-status: ${GRAD_STUDENT_API}api/v1/student/optionalprogram
  get-optional-program-details: ${GRAD_STUDENT_API}api/v1/student/optionalprogram/%s/%s
  get-student-optional-programs: ${GRAD_STUDENT_API}api/v1/student/optionalprogram/studentid/%s
  update-grad-status-algo-error: ${GRAD_STUDENT_API}api/v1/student/algorithmerror/%s?isGraduated=%s
  update-grad-status-projected: ${GRAD_STUDENT_API}api/v1/student/projected/studentid/%s
  student-for-school-report: ${GRAD_STUDENT_API}api/v1/student/batch/schoolreport/%s
  school-nongrad-year-end-students: ${GRAD_STUDENT_API}api/v1/student/studentschoolreportdata
 grad-program-api: 
  program_name_by_program_code: 
   url: ${GRAD_PROGRAM_API}api/v1/program/programs/%s
  program_requirement_codes:
   url: ${GRAD_PROGRAM_API}api/v1/program/programrequirementcode
 gradalgorithm-api: 
  gradalgorithm: ${GRAD_ALGORITHM_API}api/v1/graduatestudent?studentID=%s&gradProgram=%s
  projectedgradalgorithm: ${GRAD_ALGORITHM_API}api/v1/graduatestudent?studentID=%s&gradProgram=%s&projected=%b
 grad-graduation-report-api: 
  update-grad-student-report: 
   url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/studentreport?isGraduated=%s
  update-grad-school-report:
     url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/schoolreport
  school-year-end-students:
     url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/getstudentsforschoolyearendreport
  school-students:
    url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/getstudentsforschoolreport
  update-grad-student-transcript:
    url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/studenttranscript?isGraduated=%s
  update-grad-student-certificate: 
   url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/studentcertificate
  get-certificate-name: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/certificatetype/%s
  get-cert-list: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/programcertificates
  get-transcript: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/programtranscripts
 report-api: 
  achievement_report: ${GRAD_REPORT_API}api/v1/reports/achievementreport
  transcript_report: ${GRAD_REPORT_API}api/v1/reports/transcriptreport
  certificate_report: ${GRAD_REPORT_API}api/v1/reports/certificate
  student_non_grad: ${GRAD_REPORT_API}api/v1/reports/studentnongrad
  school_graduation: ${GRAD_REPORT_API}api/v1/reports/schoolgraduation
  school_non_graduation: ${GRAD_REPORT_API}api/v1/reports/schoolnongraduation
  school_distribution_year_end: ${GRAD_REPORT_API}api/v1/reports/schooldistributionyearend
  district_distribution_year_end: ${GRAD_REPORT_API}api/v1/reports/districtdistributionyearend
  school_labels: ${GRAD_REPORT_API}api/v1/reports/schoollabel
 grad-student-graduation-api:
  get-special-cases: 
    url: ${GRAD_STUDENT_GRADUATION_API}api/v1/studentgraduation/lgSc/specialcase/%s
 educ-school-api:
   url: ${EDUC_SCHOOL_API}api/v1/schools/%s
 pen-student-api:
   by-studentid:
     url: ${PEN_API}api/v1/student/%s
   search:
     url: ${PEN_API}api/v1/student/paginated
   by-pen:
     url: ${PEN_API}api/v1/student?pen=%s
 grad-trax-api:
   school-by-min-code:
     url: ${GRAD_TRAX_API}api/v1/trax/school/%s

#Splunk LogHelper
splunk:
  log-helper:
    enabled: ${ENABLE_SPLUNK_LOG_HELPER}
